import { Exo_2 } from 'next/font/google';
import './globals.css';
import type { Metadata } from "next";

const exo_2 = Exo_2({
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${exo_2.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
